spring.datasource.url=REPLACE YOUR URL & DB NAME
spring.datasource.username=REPLACE YOUR USERNAME
spring.datasource.password=REPLACE YOUR PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true